default_language_version:
  python: python3.8
repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 377d260ffa6f746693f97b46d95025afc4bd8275 # 5.4.2
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/psf/black
    rev: 6bedb5c58a7d8c25aa9509f8217bc24e9797e90d # 19.10b0
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 181bb46098dddf7e2d45319ea654b4b4d58c2840 # 3.8.3
    hooks:
      - id: flake8
  - repo: https://github.com/PyCQA/bandit
    rev: d25f3fc5f0f2bd8a251f252e9d81118c4947ae0e # 1.6.2
    hooks:
      - id: bandit
        exclude: tests/.*\.py
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: d6e31aeb109d8ff85282c3fd632c89f8ea7b0dee # 0.782
    hooks:
      - id: mypy
