FROM python:3.9-alpine3.15

RUN apk update && \
    apk add \
    gcc \
    g++ \
    musl-dev \
    libffi-dev \
    python3-dev \
    openssl-dev \
    && \
    pip install pipenv==2022.1.8
WORKDIR /build

COPY Pipfile Pipfile.lock ./

ARG PIPENV_PYUP_API_KEY=

RUN PIPENV_VENV_IN_PROJECT=1 \
    pipenv install --deploy && \
    pipenv check
