version: '3'
services:
  toy-manifest-service:
    image: toy-manifest-service
    build: .
    ports:
      - 4000:4000
    restart: always
    read_only: true
    volumes:
      - type: bind
        source: ./layers
        target: /layers
    tmpfs:
      - /code/.pytest_cache/
